# SELECT
# C.ID
# FROM ECOLI_DATA A # 1세대
# INNER JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID # 2세대
# INNER JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID # 3세대
# WHERE A.PARENT_ID IS NULL
# ORDER BY 1













SELECT
    # C1.PARENT_ID AS GENERATION_1,
    # C1.ID AS GENERATION_2,
    C2.ID # AS GENERATION_3
FROM ECOLI_DATA C0
INNER JOIN ECOLI_DATA C1 ON C0.ID = C1.PARENT_ID
INNER JOIN ECOLI_DATA C2 ON C1.ID = C2.PARENT_ID
WHERE C0.PARENT_ID IS NULL 
ORDER BY 1