--07_avg_units_by_day_region

WITH CLEANED AS (
  SELECT
    *,
    MAX(CLEANED_DATE) OVER (ORDER BY ROW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FILLED_DATE
  FROM (
    SELECT
      *,
      NULLIF(DATE, '-') AS CLEANED_DATE,
      ROW_NUMBER() OVER () AS ROW_ID
    FROM TEST
  )
)

SELECT
  FILLED_DATE AS DATE,
  REGION,
  AVG(beverages_units) AS TOTAL_B,
  AVG(food_units) AS TOTAL_F,
  AVG(electronics_units) AS TOTAL_E,
  AVG(clothes_units) AS TOTAL_C,
  AVG(tools_units) AS TOTAL_T
FROM CLEANED
GROUP BY FILLED_DATE, REGION
ORDER BY FILLED_DATE, REGION