-- 09_top_category_by_region.sql

WITH CLEANED AS (
	SELECT
	*,
	MAX(CLEANED_DATE) OVER (ORDER BY ROW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FILLED_DATE
	FROM (
		SELECT
		*,
		NULLIF(DATE, '-') AS CLEANED_DATE,
		row_number() OVER () AS ROW_ID
		FROM data4
		)
)

, UNPIVOTING AS (
	SELECT REGION, 'beverages' AS CATEGORY, SUM(beverages_units) AS TOTAL_UNITS 
	FROM CLEANED
	GROUP BY REGION
	
	UNION ALL
	
	SELECT REGION, 'food', SUM(food_units)
	FROM CLEANED
	GROUP BY REGION
	
	UNION ALL
	
	SELECT REGION, 'electronics', SUM(electronics_units)
	FROM CLEANED
	GROUP BY REGION
	
	UNION ALL
	
	SELECT REGION, 'clothes', SUM(clothes_units) 
	FROM CLEANED
	GROUP BY REGION
	
	UNION ALL
	
	SELECT REGION, 'tools', SUM(tools_units) 
	FROM CLEANED
	GROUP BY REGION
)

, MOST_SELL AS (
	SELECT
	*,
	ROW_NUMBER() OVER (PARTITION BY REGION ORDER BY TOTAL_UNITS DESC) AS RN
	FROM UNPIVOTING
)

SELECT
REGION,
CATEGORY,
TOTAL_UNITS
FROM MOST_SELL
WHERE RN = 1