-- 10_last_date_of_3day_increase.sql

WITH CLEANED AS (
	SELECT
	*,
	MAX(CLEANED_DATE) OVER (ORDER BY ROW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FILLED_DATE
	FROM (
		SELECT
		*,
		NULLIF(DATE, '-') AS CLEANED_DATE,
		ROW_NUMBER() OVER () AS ROW_ID
		FROM data4
		)
)

, TOTAL_SUM AS (
	SELECT
	FILLED_DATE AS DATE,
	SUM(beverages_units+food_units+electronics_units+clothes_units+tools_units) AS TOTAL
	FROM CLEANED
	GROUP BY FILLED_DATE
)

, LAGGED AS (
	SELECT
	DATE,
	TOTAL,
	LAG(TOTAL, 3) OVER (ORDER BY DATE) AS THREE,
	LAG(TOTAL, 2) OVER (ORDER BY DATE) AS TWO,
	LAG(TOTAL, 1) OVER (ORDER BY DATE) AS ONE
	FROM TOTAL_SUM
)

SELECT * FROM LAGGED
WHERE THREE < TWO AND TWO < ONE AND ONE < TOTAL
ORDER BY DATE DESC
LIMIT 1