SELECT
P.PRODUCT_CODE,
SALES_COUNT * PRICE AS SALES
FROM PRODUCT P
LEFT JOIN (
SELECT
PRODUCT_ID,
SUM(SALES_AMOUNT) AS SALES_COUNT
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID
) O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC