WITH CLEAN AS (
SELECT
FOOD_TYPE,
REST_ID,
REST_NAME,
FAVORITES,
ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
FROM REST_INFO
ORDER BY FOOD_TYPE, FAVORITES DESC
)

SELECT FOOD_TYPE,
REST_ID,
REST_NAME,
FAVORITES
FROM CLEAN
WHERE RN = 1
ORDER BY FOOD_TYPE DESC