SELECT
U.USER_ID,
U.NICKNAME,
CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
CONCAT(
    SUBSTRING(TLNO, 1, 3), '-',
    SUBSTRING(TLNO, 4, 4), '-',
    SUBSTRING(TLNO, 8, 4)
) AS '전화번호'
FROM USED_GOODS_USER U
INNER JOIN (
    SELECT WRITER_ID 
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) B ON U.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC