# SELECT
# YEAR(SALES_DATE) AS YEAR,
# MONTH(SALES_DATE) AS MONTH,
# GENDER,
# COUNT(GENDER) AS USERS
# FROM ONLINE_SALE OS
# INNER JOIN USER_INFO I
# ON I.USER_ID = OS.USER_ID
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER


SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    I.GENDER,
    COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
LEFT JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER