WITH RECURSIVE GEN_COUNT AS (
    SELECT
    ID,
    PARENT_ID,
    1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
    GN.ID,
    GN.PARENT_ID,
    G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA GN
    INNER JOIN GEN_COUNT G ON GN.PARENT_ID = G.ID
)

SELECT
COUNT(*) AS `COUNT`,
GENERATION AS GENERATION
FROM GEN_COUNT G
LEFT JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION