SELECT
    QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM (
    SELECT
    CONCAT(QUARTER(DATE_FORMAT(DIFFERENTIATION_DATE, '%Y-%m-%d')), 'Q') AS QUARTER,
    ID 
    FROM ECOLI_DATA
) AS SUB
GROUP BY QUARTER
ORDER BY QUARTER

# SELECT
# CASE WHEN Q = 1 THEN 'Q1'
#     WHEN Q = 2 THEN 'Q2'
#     WHEN Q = 3 THEN 'Q3'
#     ELSE Q4
#     END AS QUARTER,
# COUNT(ID) AS ECOLI_COUNT
# FROM (
#     SELECT
#     ID,
#     QUARTER(DATE_FORMAT(DIFFERENTIATION_DATE, '%Y-%m-%d')) AS Q
#     FROM ECOLI_DATA
#     )
# GROUP BY QUARTER