-- 코드를 입력하세요
SELECT
    APNT_NO,
    P.PT_NAME,
    P.PT_NO,
    D.MCDP_CD,
    D.DR_NAME,
    APNT_YMD
FROM APPOINTMENT A
LEFT JOIN PATIENT P ON P.PT_NO = A.PT_NO
JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE APNT_CNCL_YN != 'Y'
    AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD