# SELECT 
#     HOUR(DATETIME) AS HOUR,
#     COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY DATE_FORMAT(DATETIME, '%H')
# ORDER BY DATE_FORMAT(DATETIME, '%H') 



WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR +1 FROM HOURS WHERE HOUR < 23
)

SELECT
    LPAD(HOURS.HOUR, 2, '0') AS HOUR,
    COUNT(A.DATETIME) AS COUNT
FROM HOURS
LEFT JOIN ANIMAL_OUTS A
ON HOUR(A.DATETIME) = HOURS.HOUR
GROUP BY HOURS.HOUR
ORDER BY HOURS.HOUR