--03_min_tools_delivery_date

WITH CLEANED AS (
  SELECT
    *,
    MAX(CLEANED_DATE) OVER (ORDER BY ROW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FILLED_DATE
  FROM (
    SELECT
      *,
      NULLIF(DATE, '-') AS CLEANED_DATE,
      ROW_NUMBER() OVER () AS ROW_ID
    FROM TEST
  )
)

SELECT
  FILLED_DATE AS DATE,
  SUM(TOOLS_UNITS) AS TOTAL_TOOLS
FROM CLEANED
GROUP BY FILLED_DATE
ORDER BY TOTAL_TOOLS
LIMIT 1