--08_top_clothes_region

WITH CLEANED AS (
  SELECT
    *,
    MAX(CLEANED_DATE) OVER (ORDER BY ROW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FILLED_DATE
  FROM (
    SELECT
      *,
      NULLIF(DATE, '-') AS CLEANED_DATE,
      ROW_NUMBER() OVER () AS ROW_ID
    FROM TEST
  )
)

SELECT 
  REGION, 
  SUM(clothes_units) AS TOTAL_C 
FROM CLEANED 
GROUP BY REGION
ORDER BY TOTAL_C DESC 
LIMIT 1

-- 전체 순위 확인 시 LIMIT 1 제거