-- 11_top_25_percent_regions.sql

WITH CLEANED AS (
	SELECT
	*,
	MAX(CLEANED_DATE) OVER (ORDER BY ROW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FILLED_DATE
	FROM (
		SELECT
		*,
		NULLIF(DATE, '-') AS CLEANED_DATE,
		row_number() OVER () AS ROW_ID
		FROM data4
		)
)

, REGION_TOTAL AS (
	SELECT
	REGION,
	SUM(beverages_units + food_units + electronics_units + clothes_units + tools_units) AS TOTAL_UNITS
	FROM CLEANED
	GROUP BY REGION
)

, RANKED AS (
	SELECT
	*,
	NTILE(4) OVER (ORDER BY TOTAL_UNITS DESC) AS TILE
	FROM REGION_TOTAL
)

SELECT
REGION,
TOTAL_UNITS
FROM RANKED
WHERE TILE = 1