# SELECT
#     ID,
#     EMAIL,
#     FIRST_NAME,
#     LAST_NAME
# FROM DEVELOPERS D
# INNER JOIN SKILLCODES S
#     ON D.SKILL_CODE & S.CODE > 0
# WHERE S.CATEGORY = 'Front End'
# ORDER BY 1 ASC


SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS D
WHERE SKILL_CODE & (
    SELECT SUM(CODE) AS SUM_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    ) > 0
ORDER BY 1 ASC