SELECT
    SG.EMP_NO,
    EE.EMP_NAME,
    SG.GRADE,
    CASE WHEN SG.GRADE = 'S' THEN SAL * 0.2
        WHEN SG.GRADE = 'A' THEN SAL * 0.15
        WHEN SG.GRADE = 'B' THEN SAL * 0.1
        ELSE SAL * 0
    END AS 'BONUS'
FROM HR_EMPLOYEES EE
LEFT JOIN (
    SELECT
        EMP_NO,
        CASE WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96 THEN 'A'
            WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90 THEN 'B'
            ELSE 'C'
        END AS 'GRADE'
    FROM HR_GRADE
    GROUP BY EMP_NO
) SG ON EE.EMP_NO = SG.EMP_NO
ORDER BY EMP_NO ASC
