SELECT
    SG.EMP_NO,
    SG.EMP_NAME,
    SG.GRADE,
    CASE WHEN SG.GRADE = 'S' THEN SAL * 0.2
        WHEN SG.GRADE = 'A' THEN SAL * 0.15
        WHEN SG.GRADE = 'B' THEN SAL * 0.1
        ELSE SAL * 0
    END AS 'BONUS'
FROM HR_EMPLOYEES EE
LEFT JOIN (
    SELECT
        E.EMP_NO,
        E.EMP_NAME,
        CASE WHEN AVG(SCORE) >= 96 THEN 'S'
            WHEN AVG(SCORE) >= 90 AND AVG(SCORE) < 96 THEN 'A'
            WHEN AVG(SCORE) >= 80 AND AVG(SCORE) < 90 THEN 'B'
            ELSE 'C'
        END AS 'GRADE'
    FROM HR_EMPLOYEES E
    LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
    GROUP BY E.EMP_NO, E.EMP_NAME
) SG ON EE.EMP_NO = SG.EMP_NO AND EE.EMP_NAME = SG.EMP_NAME