WITH REVIEW_COUNT AS (
    SELECT
    MEMBER_ID,
    COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

, MAX_REVIEW AS (
    SELECT
    MEMBER_ID
    FROM REVIEW_COUNT
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNT)
)

SELECT
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (SELECT * FROM MAX_REVIEW)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
