SELECT
P.ID AS ID,
P.GENOTYPE AS GENOTYPE,
C.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA P
JOIN ECOLI_DATA C ON P.PARENT_ID = C.ID
# WHERE C.GENOTYPE & P.GENOTYPE != 0 # 부모 형질 하나라도 있으면 괜찮은 연산
# 문제는 부모 형질 "모두" 보유한 대장균
WHERE (C.GENOTYPE & P.GENOTYPE) = C.GENOTYPE
ORDER BY P.ID
