-- START DATE BETWEEN 2022-08-01 AND 2022-10-31
-- RECORDS >= 5
-- MONTH(START_DATE)
-- CAR_ID
-- RECORDS


WITH FILTERED AS (
    SELECT
    CAR_ID,
    START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
)

SELECT
MONTH(START_DATE) AS MONTH,
CAR_ID,
COUNT(CAR_ID) AS RECORDS
FROM FILTERED
WHERE CAR_ID IN (
    SELECT CAR_ID 
    FROM FILTERED 
    GROUP BY CAR_ID 
    HAVING COUNT(*) >= 5
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC