# SELECT
# ID,
# FISH_NAME,
# M.LENGTH
# FROM FISH_INFO I
# INNER JOIN ( 
#     SELECT
#     FISH_TYPE AS FISH_NAME,
#     MAX(LENGTH) AS LENGTH
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# ) M ON I.FISH_TYPE = M.FISH_NAME AND I.LENGTH = M.LENGTH
# ORDER BY ID

SELECT
II.ID,
MF.FISH_NAME,
MF.MAX_LENGTH AS LENGTH
FROM (
    SELECT
    I.FISH_TYPE,
    FISH_NAME,
    MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO I
    INNER JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY FISH_TYPE, FISH_NAME
) MF 
INNER JOIN FISH_INFO II
ON II.FISH_TYPE = MF.FISH_TYPE AND II.LENGTH = MF.MAX_LENGTH